dependencies:
  - name: postgresql
    version: 6.5.0
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: redis
    version: 9.3.2
    repository: https://kubernetes-charts.storage.googleapis.com/
